### ISSUE TITLE
HTML Purifier takes too long and page view fails (investigate)

### ISSUE THREAD

**Issue by pjotrsavitski** [centre-for-educational-technology/edidaktikum#402]
**Investigate why that happens and what the solution should be. Too long processing times are unacceptable.**

Looks like HTMLPurifier could take more than 30 seconds to process and purify the data, this makes the page fail with **Fatal error**.

Fatal error: Maximum execution time of 30 seconds exceeded in <PART-OF-PATH-REMOVED>/htmlpurifier/library/HTMLPurifier/PercentEncoder.php on line 63

The issue raised with: http://edidaktikum.ee/et/content/eky6001-practical-estonian-a1

The **body** to be purified seems to be empty, this makes it especially strange that the processing time is se long.

**Temporaty solution (probably)**: increased script execution time to 60 seconds from default value of 30. Change made in .htaccess file.

**Comment by GlebRed** [comment]
`php_value max_execution_time` reduced to `40` in .htaccess file

Issue not related to HTMLPurifier.

The issue is related to the fact that the group page loads data from nodes related to that group. One of these nodes http://edidaktikum.ee/et/node/10728 had a corrupted image inserted into ed_content field body and encoded in base64. This resulted in 13.5 seconds HTMLPurifier was taking to analyse a 7.1 MB image. The other 2 places that slow down HTMLPurifier (by max 4.9 seconds) are improperly inserted data from Word.

**Comment by pjotrsavitski** [comment]
I'd say leave it be at 60 seconds. There might be some more cases that would benefit from it.

**Comment by GlebRed** [comment]
Returned to `60`
